#Configuration options for the vore plugin

#Note: if a value is unreadable it will be reset to default

#---------- General Configs ----------

bellyMax: 64

turduckenLimit: 10

forceAutoReform: false