name: VorePlugin
version: 2.1.0-DEV
main: me.endermenskill.voreplugin.VorePlugin
api-version: 1.20
authors: [Endermenskill]
softdepend: [PlaceholderAPI]
description: A plugin to bring the joys of vor eto the world of Minecraft.
commands:
  setbelly:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <name> <type>"
    description: Sets the given belly to the player's location.
  setrank:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <PlayerRank>"
    description: Sets the player's rank.
  digest:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <name>"
    description: Digests the given player or all players you have swallowed.
  release:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <name>"
    description: Releases the given player or all players you have swallowed.
  belly:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <belly> <path> <value>"
    description: Allows you to edit various paramaters of your belly.
  preference:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <add|remove> <voreType>"
    description: Set a blacklist of vore types you don't want to participate in.
  vorestats:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <name>"
    description: View vore related statistics.
  voretop:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <category>"
    description: View the vore stats leaderboards.
  vore:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command> <branch> <arguments>"
    description: Command to set bellies, set and vore types vore ranks, set and view preference settings set and view stats and leaderboards.
  version:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command>"
    description: Returns the plugin's version
  disposal:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command>"
    description: For the disposal enjoyers ;)
  test:
    usage: "§8[§b§lVorePlugin§8] §7Usage: /<command>"
    description: Super secret testing command so don't tell anyone!